# Generated by Django 3.2.9 on 2021-12-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_alter_document_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
