# Generated by Django 3.2.9 on 2021-12-14 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_auto_20211214_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='product',
        ),
        migrations.AddField(
            model_name='history',
            name='document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='document.document', verbose_name='dokument'),
            preserve_default=False,
        ),
    ]
