# Generated by Django 3.2.9 on 2021-12-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_auto_20211214_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=80, verbose_name='nazwa produktu ubezpieczeniowego'),
        ),
    ]
