# Generated by Django 3.2.9 on 2021-12-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0009_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(max_length=20, verbose_name='model przepływów pieniężnych'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=60, verbose_name='nazwa produktu ubezpieczeniowego'),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('product', 'category', 'validity_start')},
        ),
    ]
