# Generated by Django 3.2.9 on 2022-01-15 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0010_auto_20211218_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
    ]
